### ISSUE TITLE
[Bug] BitcoinCash balance parsing failed

### ISSUE THREAD

**Issue by Bastien-Satochip** [Toporin/Satodime-Android#28]
The Bitcoin Cash value is not parsed correctly. 
If the balance is lower than 0 BCH, it shows 0 BCH instead of 0.002 BCH for example.

Android: 
![image](https://github.com/Toporin/Satodime-Android/assets/87421384/6408f54b-ad28-4f6c-87ed-e9b07ce5b6dd)

iOS, for the same card: 
![image](https://github.com/Toporin/Satodime-Android/assets/87421384/7426806b-9b4a-4e8e-8f82-15121ecdfd72)

**Comment by Toporin** [comment]
corrected in 5796c74
