### ISSUE TITLE
[Modification of a link] “Plus d'info” / “More info” link on the third onboarding screen.

### ISSUE THREAD

**Issue by Toporin** [Toporin/Satodime-Android#5]
Would it be possible to modify the link on the third onboarding screen - “Plus d'info” button (FR) / “More info” (EN)

Point to the explanatory Youtube video:
[Discover the Satodime Mobile App | Complete Tutorial](https://www.youtube.com/watch?v=Z4vfEqtQleg&t=84s)

Take this link, which includes the exact second in the video explaining why and how to scan your card correctly.

**Comment by Bastien-Satochip** [comment]
[13-05-2024] Update following the meeting.

Add another button that will point to the video tutorial (Youtube).
And leave the actual button as is; pointing to the current URL.

**Comment by Bastien-Satochip** [comment]
This issue can be closed... Done in Satodime_Android_v0.3.0
Tested successfully on the 20/06/2024
