### ISSUE TITLE
[Nice-to-Have] Better look and feel for the NFC toast.

### ISSUE THREAD

**Issue by Toporin** [Toporin/Satodime-Android#6]
On iOS, there is a native NFC toast functionnality that look like this: (see the video).

https://github.com/Toporin/Satodime-Android/assets/10826856/5862b165-807a-4358-b407-35343bba177b

1) The user click on the “Click & Scan” button
2) It calls the NFC functionnality and prompt the user to scan the card.
This toast is composed like:
- A title “Ready to Scan”
- An animation showing the phone
- A sub-text (the message may vary) “Hold you Satodime near iPhone”
- A cancel button
3) The user scan his card (and leave the card on the reader throughout the operation. So the card is beeing read.
4) Then the toast say that everything goes well or wrong.
This toast is composed like:
- An animation showing a blue check mark
- A sub-text (the message may vary) “Listed vaults successfully!”

We would like to make the current “Android toast” functionnality (that is not native) more “iOS” like.

We can either keep to current way it is done :

* please scan the card
* card beeing read
* Ok card read

Or just like iPhone is doing with a “Ready to scan message” followed by a blue check.

Up to you, we can discuss it during a quick meeting.

![image (1)](https://github.com/Toporin/Satodime-Android/assets/10826856/304071ad-334d-4c49-b999-08961180f5e9)
![image (2)](https://github.com/Toporin/Satodime-Android/assets/10826856/d923b803-d4d0-4b20-a1aa-e59f5d453218)

**Comment by Bastien-Satochip** [comment]
This issue can be closed... Done in Satodime_Android_v0.3.0
Tested successfully on the 20/06/2024
