### ISSUE TITLE
[Add functionality] Rate my app

### ISSUE THREAD

**Issue by Toporin** [Toporin/Satodime-Android#8]
Allow the user to rate the application in the Google Playstore after X use of the application. This feature will help to better rank the app in the PlayStore.

Something like the screenshot below would be great:
1) After 10 or 20 launches of the app, prompt the user to rate the app.
2) If he declined, remind him after 10 or 20 launches

![Sans titre 1](https://github.com/Toporin/Satodime-Android/assets/10826856/a1474e39-9f17-4d96-9a66-bb3bb657edb2)

**Comment by Bastien-Satochip** [comment]
This issue can be closed... Done in Satodime_Android_v0.3.0
Tested successfully on the 20/06/2024
