### ISSUE TITLE
[Add functionality] Polygon blockchain support

### ISSUE THREAD

**Issue by Toporin** [Toporin/Satodime-Android#9]
Implement the Polygon blockchain into the Android Satodime mobile app.
See the checklist for more information.

Requirements:
[GitHub - Toporin/Javacryptotools: Javacryptotools - simple java library for crypto coins integration](https://github.com/Toporin/Javacryptotools)

This librairy needs to be modify to integrate Polygon API and explorer.
See the Polygon support commit from the iOS team for more information: [Comparing master...dev/Polygon-support · Toporin/SwiftCryptoTools](https://github.com/Toporin/SwiftCryptoTools/compare/master...dev/Polygon-support)

The Polygon logo is attached.

Checklist:
* Adapt the JavaCryptoTools to integrate the Polygon blockchain API.
* Integrate Polygon (MainNet & TestNet) into Satodime.
* Add the needed screen to seal a new keyslot
* Test to sealing procedure.

[Polygon logo.zip](https://github.com/Toporin/Satodime-Android/files/15231789/Polygon.logo.zip)

**Comment by Bastien-Satochip** [comment]
This issue can be closed... Done in Satodime_Android_v0.3.0
Tested successfully on the 20/06/2024
